### ISSUE TITLE
Decks' display

### ISSUE THREAD

**Issue by SantiGarciaG** [SantiGarciaG/AA_expII#3]
I tried to make the deck contingent on leaving the defined "dead zone" area, but for some reason it is not working: They are still appearing upon leaving the "start button area".

I have marked this code with "# ************"

And I guess the delayed response alert tone might be deactivated then (???)

**Comment by SantiGarciaG** [comment]
There seems to be a problem with the changes we made to make the deck appear upon leaving the start area, it seems to work for the first block, but afterwards one sees the decks already displayed and with the previous values, then on leaving the start area, what changes is the values.

**Comment by cherepaha** [comment]
Seems to be fixed now, can you check this please? Worked for me when I had two blocks
