### ISSUE TITLE
terminating the experiment 

### ISSUE THREAD

**Issue by SantiGarciaG** [SantiGarciaG/AA_expII#6]
I wonder if when we modified the block_info last time, we altered the way the experiment is to terminate upon switching. As a matter of fact, it does not finished ever anymore!!

**Comment by cherepaha** [comment]
There was a problem with passing p_threat to run_exp, which is now fixed (can you please check if this works as expected).

However, after taking a closer look at this, I'm not sure anymore whether I actually remember/understand the logic of experiment termination. Can you remind me what we should do if

1. Participant has p_threat > 0.5 in the very first block (do we start "reversed" sequence at all in this case? right now it does run regardless the outcome of the forward sequence)
2. Participant keeps going "back" in "reversed" sequence (in other words, participant always prefers threat). Theoretically, we should decrease the reward for the threat stimulus (until what point?), and also check after each block whether the maximum number of blocks was reached (right now this check is not performed)
3. Related question: should our MAX_N_BLOCKS define maximum number of blocks within the whole experiment or within each of the forward and reversed sequences?

**Comment by SantiGarciaG** [comment]
The funny thing is that, as far as I tested the previous version, all of this was actually working before the last changes. About your questions:

1. if p_threat >= 0.5, then for the next block we decrease the rewards (yes, even if this happens during the first experimental block; which would mean of course that somebody who isn't afraid would then have to choose between 10 vs. 10 in the next block, but remember that we are not that interested in these individuals). But see issue on method of limits, we decrease the threat option when this is preferred, and we increase the threat option when the safe is preferred (this is now corrupted). 

2. If a participant decides to prefer the threat (regardless of the fact that this would eventually give less points than the safe option) the further s/he can go is the blocks (I think was one of the functions of the MAX_N_BLOCKS constant). 

3. Good question. I think we initially thought to apply this for the whole experiment (thinking that this would mean reaching 10 vs. 30, but it doesn't work of course if we count "backwards" blocks). Remember that the experiment is supposed to finished under one of two conditions: a) a participant goes all the way avoiding until 10 vs 30 (or whatever the max possible higher points are); b) when a participant has "switched" twice (e.g., from avoiding to approaching, and then again from approaching to avoiding), assuming a fearful participant. A participant who isn't afraid and therefore always chooses threat, should then be expected to switch back after the 2nd/3rd block (not going indefinitely backwards!)

**Comment by cherepaha** [comment]
Yep, when we coded this yesterday, we introduced a small bug which however affected the flow of the experiment in a major way. Basically, our changes led to p_threat being always greater than 1, which meant that the experiment would continue indefinitely. This is now fixed, though. Regarding the stopping rules:

1. Got it, this is how it works now.
2 and 3. A recent update introduces MAX_N_BLOCKS to the reversed sequence. If I got you point, MAX_N_BLOCKS defines maximum number of blocks in each sequence. For example, if MAX_N_BLOCKS is 10, the participant can then go up to 10 vs 28 in the forward sequence, and then will be able to go back, say, to 10 vs 10 (but not lower, as this would require more than 10 blocks), yielding lower bound of 10 and upper bound of 28. Is that right?

**Comment by SantiGarciaG** [comment]
In the last version that just pull, when I then switch from approach to avoidance, preferring the safe option keep on decreasing the threat option value (when it should lead to increase the threat option).

Regarding the MAX_N_BLOCKS I think you're correct, assuming the experiment doesn't terminate sooner due to the switches (see issue #7 ). So the participant could prefer the safe option all the way up to 10 vs 30 (N_BLOCKS = 10), in which case we won't really have any bounds, or if it were to go backwards as you say upon reaching 10vs28, that person's upper bound would be 28 (as it is the first switch from avoidance to approach) and, assuming that that person keeps on going backwards (i.e., maintains preference to the threat) I guess when it reaches 10vs10 it would've run out of blocks and therefore no lower bound would be recorded. But if the person then switches back to the safe option, e.g., once the threat value has decreased to 10vs26, then his lower bound would be 26.

**Comment by cherepaha** [comment]
> In the last version that just pull, _when I then switch from approach to avoidance_, preferring the safe option keep on decreasing the threat option value (when _it should lead to increase the threat option_).

Ok, then I guess it has more to do with Issue #7, which I hopefully fixed now.
